name: CI

on:
  pull_request:
    branches:
      - main
  push:

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
  cancel-in-progress: true

jobs:
  lint-report:
    name: Lint report
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e lint

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e static

  unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e unit

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install tox
        run: pip install tox
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.29-strict/stable
          juju-channel: 3.4/stable
          lxd-channel: 5.20/stable
      - name: Run tests using tox
        run: tox -e integration
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz

  publish-charm:
    name: Publish Charm
    needs: integration-tests
    runs-on: ubuntu-22.04
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Select Charmhub channel
        uses: canonical/charming-actions/channel@2.4.0
        id: channel
      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.4.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"

  publish-lib:
    runs-on: ubuntu-22.04
    name: Charmhub upload lib
    needs:
      - publish-charm
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish libs
        uses: canonical/charming-actions/release-libraries@2.4.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
